_STATE_DOI_DOCS = [
    {
        "name": "Alabama Department of Insurance Overview",
        "source": "Alabama Department of Insurance",
        "url": "https://aldoi.gov/",
        "local_name": "alabama/alabama_doi_overview.txt",
        "description": "Official Alabama Department of Insurance overview page.",
    },
    {
        "name": "Alaska Division of Insurance Overview",
        "source": "Alaska Division of Insurance",
        "url": "https://www.commerce.alaska.gov/web/ins/",
        "local_name": "alaska/alaska_doi_overview.txt",
        "description": "Official Alaska Division of Insurance overview page.",
    },
    {
        "name": "Arizona Insurance and Storms or Disasters Guide",
        "source": "Arizona Department of Insurance and Financial Institutions",
        "url": "https://difi.az.gov/sites/default/files/INSURANCE%20%26%20STORMS%20OR%20DISASTERS%20%281%29.pdf",
        "local_name": "arizona/arizona_insurance_storms_disasters_guide.pdf",
        "description": "Official Arizona DIFI consumer guide on insurance and storms or disasters.",
        "manifest_only": True,
    },
    {
        "name": "Arkansas Insurance Department Consumer Services",
        "source": "Arkansas Insurance Department",
        "url": "https://insurance.arkansas.gov/pages/consumer-services/",
        "local_name": "arkansas/arkansas_doi_consumer_services.txt",
        "description": "Official Arkansas consumer services page.",
        "manifest_only": True,
    },
    {
        "name": "California Department of Insurance Overview",
        "source": "California Department of Insurance",
        "url": "https://www.insurance.ca.gov/",
        "local_name": "california/california_doi_overview.txt",
        "description": "Official California Department of Insurance overview page.",
    },
    {
        "name": "Colorado Division of Insurance Consumer Page",
        "source": "Colorado Division of Insurance",
        "url": "https://doi.colorado.gov/for-consumers",
        "local_name": "colorado/colorado_doi_consumers.txt",
        "description": "Official Colorado Division of Insurance consumer page.",
    },
    {
        "name": "Connecticut Insurance Department Overview",
        "source": "Connecticut Insurance Department",
        "url": "https://portal.ct.gov/cid",
        "local_name": "connecticut/connecticut_doi_overview.txt",
        "description": "Official Connecticut Insurance Department overview page.",
    },
    {
        "name": "Delaware Department of Insurance Overview",
        "source": "Delaware Department of Insurance",
        "url": "https://insurance.delaware.gov/",
        "local_name": "delaware/delaware_doi_overview.txt",
        "description": "Official Delaware Department of Insurance overview page.",
    },
    {
        "name": "Florida Office of Insurance Regulation Overview",
        "source": "Florida Office of Insurance Regulation",
        "url": "https://floir.gov/",
        "local_name": "florida/florida_doi_overview.txt",
        "description": "Official Florida Office of Insurance Regulation overview page.",
    },
    {
        "name": "Georgia Office of Commissioner of Insurance Overview",
        "source": "Georgia Office of Commissioner of Insurance and Safety Fire",
        "url": "https://oci.georgia.gov/",
        "local_name": "georgia/georgia_doi_overview.txt",
        "description": "Official Georgia insurance regulator overview page.",
    },
    {
        "name": "Hawaii Insurance Division Overview",
        "source": "Hawaii Department of Commerce and Consumer Affairs Insurance Division",
        "url": "https://cca.hawaii.gov/ins/",
        "local_name": "hawaii/hawaii_doi_overview.txt",
        "description": "Official Hawaii Insurance Division overview page.",
    },
    {
        "name": "Idaho Department of Insurance Overview",
        "source": "Idaho Department of Insurance",
        "url": "https://doi.idaho.gov/",
        "local_name": "idaho/idaho_doi_overview.txt",
        "description": "Official Idaho Department of Insurance overview page.",
    },
    {
        "name": "Illinois Department of Insurance Overview",
        "source": "Illinois Department of Insurance",
        "url": "https://idoi.illinois.gov/",
        "local_name": "illinois/illinois_doi_overview.txt",
        "description": "Official Illinois Department of Insurance overview page.",
    },
    {
        "name": "Indiana Department of Insurance Overview",
        "source": "Indiana Department of Insurance",
        "url": "https://www.in.gov/idoi/",
        "local_name": "indiana/indiana_doi_overview.txt",
        "description": "Official Indiana Department of Insurance overview page.",
    },
    {
        "name": "Iowa Insurance Division Overview",
        "source": "Iowa Insurance Division",
        "url": "https://iid.iowa.gov/",
        "local_name": "iowa/iowa_doi_overview.txt",
        "description": "Official Iowa Insurance Division overview page.",
    },
    {
        "name": "Kansas Insurance Department Consumer Page",
        "source": "Kansas Insurance Department",
        "url": "https://www.insurance.kansas.gov/consumers/",
        "local_name": "kansas/kansas_doi_consumers.txt",
        "description": "Official Kansas Insurance Department consumer page.",
        "manifest_only": True,
    },
    {
        "name": "Kentucky Department of Insurance Overview",
        "source": "Kentucky Department of Insurance",
        "url": "https://insurance.ky.gov/",
        "local_name": "kentucky/kentucky_doi_overview.txt",
        "description": "Official Kentucky Department of Insurance overview page.",
    },
    {
        "name": "Louisiana Consumer's Guide to Auto Insurance",
        "source": "Louisiana Department of Insurance",
        "url": "https://www.ldi.la.gov/docs/default-source/documents/publicaffairs/consumerpublications/consumer%27s-guide-to-auto-insurance.pdf",
        "local_name": "louisiana/louisiana_consumers_guide_to_auto_insurance.pdf",
        "description": "Official Louisiana Department of Insurance consumer guide to auto insurance.",
    },
    {
        "name": "Maine Bureau of Insurance Overview",
        "source": "Maine Bureau of Insurance",
        "url": "https://www.maine.gov/pfr/insurance/home",
        "local_name": "maine/maine_doi_overview.txt",
        "description": "Official Maine Bureau of Insurance overview page.",
    },
    {
        "name": "Maryland Insurance Administration Overview",
        "source": "Maryland Insurance Administration",
        "url": "https://insurance.maryland.gov/",
        "local_name": "maryland/maryland_doi_overview.txt",
        "description": "Official Maryland Insurance Administration overview page.",
    },
    {
        "name": "Massachusetts Division of Insurance Homeowners Insurance Page",
        "source": "Massachusetts Division of Insurance",
        "url": "https://www.mass.gov/info-details/homeowners-insurance",
        "local_name": "massachusetts/massachusetts_homeowners_insurance.txt",
        "description": "Official Massachusetts homeowners insurance information page.",
        "manifest_only": True,
    },
    {
        "name": "Michigan Department of Insurance and Financial Services Overview",
        "source": "Michigan Department of Insurance and Financial Services",
        "url": "https://www.michigan.gov/difs",
        "local_name": "michigan/michigan_doi_overview.txt",
        "description": "Official Michigan DIFS overview page.",
    },
    {
        "name": "Minnesota Department of Commerce Insurance Page",
        "source": "Minnesota Department of Commerce",
        "url": "https://mn.gov/commerce/insurance/",
        "local_name": "minnesota/minnesota_insurance_page.txt",
        "description": "Official Minnesota insurance page under the Department of Commerce.",
    },
    {
        "name": "Mississippi Consumer Quick Guide to Home Insurance",
        "source": "Mississippi Insurance Department",
        "url": "https://www.mid.ms.gov/wp-content/uploads/2024/01/ConsumerQuickGuideToHomeInsurance.pdf",
        "local_name": "mississippi/mississippi_consumer_quick_guide_home_insurance.pdf",
        "description": "Official Mississippi Insurance Department quick guide to home insurance.",
        "verify_ssl": False,
    },
    {
        "name": "Missouri Department of Commerce and Insurance Consumer Page",
        "source": "Missouri Department of Commerce and Insurance",
        "url": "https://insurance.mo.gov/consumers/",
        "local_name": "missouri/missouri_doi_consumers.txt",
        "description": "Official Missouri insurance consumer page.",
        "manifest_only": True,
    },
    {
        "name": "Montana State Auditor Insurance Page",
        "source": "Montana State Auditor, Commissioner of Securities and Insurance",
        "url": "https://csimt.gov/your-insurance/",
        "local_name": "montana/montana_doi_insurance_page.txt",
        "description": "Official Montana insurance consumer page.",
    },
    {
        "name": "Nebraska Department of Insurance Overview",
        "source": "Nebraska Department of Insurance",
        "url": "https://doi.nebraska.gov/",
        "local_name": "nebraska/nebraska_doi_overview.txt",
        "description": "Official Nebraska Department of Insurance overview page.",
    },
    {
        "name": "Nevada Division of Insurance Overview",
        "source": "Nevada Division of Insurance",
        "url": "https://doi.nv.gov/",
        "local_name": "nevada/nevada_doi_overview.txt",
        "description": "Official Nevada Division of Insurance overview page.",
    },
    {
        "name": "New Hampshire Insurance Department Consumers Page",
        "source": "New Hampshire Insurance Department",
        "url": "https://www.nh.gov/insurance/consumers/index.htm",
        "local_name": "new_hampshire/new_hampshire_doi_consumers.txt",
        "description": "Official New Hampshire insurance consumers page.",
        "manifest_only": True,
    },
    {
        "name": "New Jersey Department of Banking and Insurance Overview",
        "source": "New Jersey Department of Banking and Insurance",
        "url": "https://www.nj.gov/dobi/",
        "local_name": "new_jersey/new_jersey_doi_overview.txt",
        "description": "Official New Jersey Department of Banking and Insurance overview page.",
    },
    {
        "name": "New Mexico Office of Superintendent of Insurance Overview",
        "source": "New Mexico Office of Superintendent of Insurance",
        "url": "https://www.osi.state.nm.us/",
        "local_name": "new_mexico/new_mexico_doi_overview.txt",
        "description": "Official New Mexico Office of Superintendent of Insurance overview page.",
    },
    {
        "name": "New York Homeowners Insurance Coverage Guide",
        "source": "New York State Department of Financial Services",
        "url": "https://www.dfs.ny.gov/consumers/help_for_homeowners/insurance/basic_coverage",
        "local_name": "new_york/new_york_homeowners_basic_coverage.txt",
        "description": "Official New York homeowners and tenants insurance coverage guide.",
    },
    {
        "name": "North Carolina Department of Insurance Overview",
        "source": "North Carolina Department of Insurance",
        "url": "https://www.ncdoi.gov/",
        "local_name": "north_carolina/north_carolina_doi_overview.txt",
        "description": "Official North Carolina Department of Insurance overview page.",
    },
    {
        "name": "North Dakota Insurance Department Overview",
        "source": "North Dakota Insurance Department",
        "url": "https://www.insurance.nd.gov/",
        "local_name": "north_dakota/north_dakota_doi_overview.txt",
        "description": "Official North Dakota Insurance Department overview page.",
    },
    {
        "name": "Ohio Department of Insurance Consumer Services Page",
        "source": "Ohio Department of Insurance",
        "url": "https://gateway.insurance.ohio.gov/UI/ODI.CS.Public.UI/Comment.mvc/DisplayCommentSubmission",
        "local_name": "ohio/ohio_doi_consumer_services.txt",
        "description": "Official Ohio Department of Insurance consumer services page.",
    },
    {
        "name": "Oklahoma Insurance Department Consumer Assistance Page",
        "source": "Oklahoma Insurance Department",
        "url": "https://www.oid.ok.gov/consumers/consumer-assistance/",
        "local_name": "oklahoma/oklahoma_doi_consumer_assistance.txt",
        "description": "Official Oklahoma consumer assistance page.",
    },
    {
        "name": "Oregon Division of Financial Regulation Insurance Page",
        "source": "Oregon Division of Financial Regulation",
        "url": "https://dfr.oregon.gov/insure/",
        "local_name": "oregon/oregon_doi_insurance_page.txt",
        "description": "Official Oregon insurance information page.",
    },
    {
        "name": "Pennsylvania Insurance Department Overview",
        "source": "Pennsylvania Insurance Department",
        "url": "https://www.insurance.pa.gov/",
        "local_name": "pennsylvania/pennsylvania_doi_overview.txt",
        "description": "Official Pennsylvania Insurance Department overview page.",
    },
    {
        "name": "Rhode Island Insurance Overview",
        "source": "Rhode Island Department of Business Regulation Insurance Division",
        "url": "https://dbr.ri.gov/insurance-overview",
        "local_name": "rhode_island/rhode_island_doi_overview.txt",
        "description": "Official Rhode Island insurance overview page.",
    },
    {
        "name": "South Carolina Department of Insurance Overview",
        "source": "South Carolina Department of Insurance",
        "url": "https://www.doi.sc.gov/",
        "local_name": "south_carolina/south_carolina_doi_overview.txt",
        "description": "Official South Carolina Department of Insurance overview page.",
    },
    {
        "name": "South Dakota Division of Insurance Overview",
        "source": "South Dakota Division of Insurance",
        "url": "https://dlr.sd.gov/insurance/",
        "local_name": "south_dakota/south_dakota_doi_overview.txt",
        "description": "Official South Dakota Division of Insurance overview page.",
    },
    {
        "name": "Tennessee Insurance Consumer Resources",
        "source": "Tennessee Department of Commerce and Insurance",
        "url": "https://www.tn.gov/commerce/insurance/consumer-resources.html",
        "local_name": "tennessee/tennessee_doi_consumer_resources.txt",
        "description": "Official Tennessee insurance consumer resources page.",
        "manifest_only": True,
    },
    {
        "name": "Texas Department of Insurance Overview",
        "source": "Texas Department of Insurance",
        "url": "https://www.tdi.texas.gov/",
        "local_name": "texas/texas_doi_overview.txt",
        "description": "Official Texas Department of Insurance overview page.",
    },
    {
        "name": "Utah Insurance Department Consumer Complaint Form",
        "source": "Utah Insurance Department",
        "url": "https://insurance.utah.gov/wp-content/uploads/UIDComplaintForm.pdf",
        "local_name": "utah/utah_doi_consumer_complaint_form.pdf",
        "description": "Official Utah Insurance Department consumer complaint form PDF.",
    },
    {
        "name": "Vermont Consumer Advisory on Rising Insurance Premiums",
        "source": "Vermont Department of Financial Regulation",
        "url": "https://dfr.vermont.gov/consumer-alert/consumer-advisory-rising-insurance-premiums",
        "local_name": "vermont/vermont_consumer_advisory_rising_premiums.txt",
        "description": "Official Vermont consumer advisory about auto and homeowners premium increases.",
    },
    {
        "name": "Virginia Bureau of Insurance Overview",
        "source": "Virginia Bureau of Insurance",
        "url": "https://scc.virginia.gov/pages/Bureau-of-Insurance",
        "local_name": "virginia/virginia_doi_overview.txt",
        "description": "Official Virginia Bureau of Insurance overview page.",
    },
    {
        "name": "Washington Office of the Insurance Commissioner Overview",
        "source": "Washington Office of the Insurance Commissioner",
        "url": "https://www.insurance.wa.gov/",
        "local_name": "washington/washington_doi_overview.txt",
        "description": "Official Washington OIC overview page.",
    },
    {
        "name": "West Virginia Offices of the Insurance Commissioner Overview",
        "source": "West Virginia Offices of the Insurance Commissioner",
        "url": "https://www.wvinsurance.gov/",
        "local_name": "west_virginia/west_virginia_doi_overview.txt",
        "description": "Official West Virginia insurance regulator overview page.",
    },
    {
        "name": "Wisconsin Office of the Commissioner of Insurance Overview",
        "source": "Wisconsin Office of the Commissioner of Insurance",
        "url": "https://oci.wi.gov/",
        "local_name": "wisconsin/wisconsin_doi_overview.txt",
        "description": "Official Wisconsin OCI overview page.",
    },
    {
        "name": "Wyoming Department of Insurance Overview",
        "source": "Wyoming Department of Insurance",
        "url": "https://doi.wyo.gov/",
        "local_name": "wyoming/wyoming_doi_overview.txt",
        "description": "Official Wyoming Department of Insurance overview page.",
    },
]

STATE_DOI_POLICY_CURATION = {
    "arizona/arizona_insurance_storms_disasters_guide.pdf": {
        "source_type": "consumer_guide",
        "policy_interpretation_tier": "core_explainer",
        "rag_role": "supplemental_explainer",
        "download_policy": "pointer_only",
    },
    "louisiana/louisiana_consumers_guide_to_auto_insurance.pdf": {
        "source_type": "consumer_guide",
        "policy_interpretation_tier": "core_explainer",
        "rag_role": "supplemental_explainer",
        "download_policy": "download",
    },
    "massachusetts/massachusetts_homeowners_insurance.txt": {
        "source_type": "coverage_explainer",
        "policy_interpretation_tier": "core_explainer",
        "rag_role": "supplemental_explainer",
        "download_policy": "pointer_only",
    },
    "mississippi/mississippi_consumer_quick_guide_home_insurance.pdf": {
        "source_type": "consumer_guide",
        "policy_interpretation_tier": "core_explainer",
        "rag_role": "supplemental_explainer",
        "download_policy": "download",
    },
    "vermont/vermont_consumer_advisory_rising_premiums.txt": {
        "source_type": "consumer_advisory",
        "policy_interpretation_tier": "supplemental_explainer",
        "rag_role": "supplemental_explainer",
        "download_policy": "download",
    },
}


def _curate_state_doi_docs(docs):
    curated = []
    for doc in docs:
        entry = dict(doc)
        curation = {
            "source_type": "regulator_portal",
            "policy_interpretation_tier": "reference_only",
            "rag_role": "exclude_from_rag",
            "download_policy": "pointer_only",
        }
        curation.update(STATE_DOI_POLICY_CURATION.get(entry["local_name"], {}))
        entry.update(curation)
        if entry.get("download_policy") != "download":
            entry["manifest_only"] = True
        curated.append(entry)
    return curated


STATE_DOI_DOCS = _curate_state_doi_docs(_STATE_DOI_DOCS)
